DROP TABLE DIMENSION_PRODUCT;
DROP TABLE DIMENSION_TIME;
DROP TABLE DIMENSION_STORE;
DROP TABLE DIMENSION_SUPPLIER;
DROP TABLE DIMENSION_CUSTOMER;
DROP TABLE FACT_SALES;
-- if error, implement the above code to clear the table and then run creatDW again.
CREATE TABLE DIMENSION_PRODUCT(
  "PRODUCT_ID"   VARCHAR2(6),
  "PRODUCT_NAME" VARCHAR2(30),
  "PRICE"        NUMBER(5,2),
  CONSTRAINT PRODUCT_ID_PKID PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DIMENSION_TIME(
  T_DATE        DATE,  
  T_DATE_YEAR   NUMBER,
  T_DAY         VARCHAR2(30),
  T_WEEK        NUMBER(10,0),
  T_MONTH       NUMBER,
  T_QUARTER     NUMBER(10,0),
  T_YEAR        NUMBER(10,0),
  CONSTRAINT T_DATE_PKID PRIMARY KEY (T_DATE)
);

CREATE TABLE DIMENSION_STORE(
  "STORE_ID"     VARCHAR2(4), 
  "STORE_NAME"   VARCHAR2(20),
  CONSTRAINT STORE_ID_PKID PRIMARY KEY (STORE_ID)
);

CREATE TABLE DIMENSION_SUPPLIER(
  "SUPPLIER_ID"   VARCHAR2(5), 
  "SUPPLIER_NAME" VARCHAR2(30),
  CONSTRAINT SUPPLIER_ID_PKID PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE DIMENSION_CUSTOMER(
  "CUSTOMER_ID"   VARCHAR2(4),
  "CUSTOMER_NAME" VARCHAR2(30),
  CONSTRAINT CUSTOMER_ID_PKID PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE FACT_SALES(
  "STORE_ID"    VARCHAR2(5), 
  "SUPPLIER_ID" VARCHAR2(5),
  "PRODUCT_ID"  VARCHAR2(6),
  "CUSTOMER_ID" VARCHAR2(4),
  "T_DATE"      DATE,
  "QUANTITY"    NUMBER(3,0),
  "SALES"       NUMBER(5,2),
  CONSTRAINT FACT_PRODUCT_ID_FKID FOREIGN KEY (PRODUCT_ID) REFERENCES DIMENSION_PRODUCT (PRODUCT_ID),
  CONSTRAINT FACT_T_DATE_FKID FOREIGN KEY (T_DATE) REFERENCES DIMENSION_TIME(T_DATE),
  CONSTRAINT FACT_STORE_ID_FKID FOREIGN KEY (STORE_ID) REFERENCES DIMENSION_STORE(STORE_ID),
  CONSTRAINT FACT_SUPPLIER_ID_FKID FOREIGN KEY (SUPPLIER_ID) REFERENCES DIMENSION_SUPPLIER (SUPPLIER_ID),
  CONSTRAINT FACT_CUSTOMER_ID_FKID FOREIGN KEY (CUSTOMER_ID) REFERENCES DIMENSION_CUSTOMER (CUSTOMER_ID)
);
